package org.myshop.storage;

import org.myshop.enums.*;
import org.myshop.products.*;

import java.util.ArrayList;
import java.util.Arrays;

/*здесь создаются объекты(=товары). класс имеет один метод, возвращающий список объектов*/

public class ProductCreator {
    public ArrayList<IProduct> createNewGoodsList() {
        ArrayList<IProduct> goodsArrList = new ArrayList<>();

        IProduct game1 = new Game.PSGameBuilder()
                .withID("G-0001")
                .withNomenclature("Last of Us")
                .withPrice(4500)
                .withProducer("NaughtyDog")
                .withRating(10)
                .withRemain(20)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.GAME)
                .withKeyWords(Arrays.asList(Keywords.AAA, Keywords.GOTY, Keywords.PS4))
                .withDescription("приключенческий экшен, рассказывающий историю Джоэла и Элли, стремящихся выжить в разрушенном, пораженном страшной эпидемией мире. Паре героев предстоит пересечь разрушенные США, чтобы добраться до безопасной зоны и спасти свои жизни.")
                .withGenre(Genre.Action)
                .withRatingPEGI(PEGI.PEGI18)
                .build();
        IProduct game2 = new Game.PSGameBuilder()
                .withID("G-0002")
                .withNomenclature("Witcher3")
                .withPrice(1000)
                .withProducer("CD Projekt RED")
                .withRating(10)
                .withRemain(40)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.GAME)
                .withKeyWords(Arrays.asList(Keywords.AAA, Keywords.GOTY, Keywords.PS4))
                .withDescription("компьютерная ролевая игра по мотивам серии романов «Ведьмак» польского писателя Анджея Сапковского, продолжение игр «Ведьмак» и «Ведьмак 2: Убийцы королей». Заключительная часть трилогии. Игроку вновь отводится роль Геральта, ведьмака, убивающего монстров. После событий второй части Геральт возвращает утраченные воспоминания, и оказывается на перепутье. В Северных королевствах бушует война, а неожиданно вернувшаяся Йеннифэр, подруга Геральта, просит его помочь с поисками Цириллы, Дитя-неожиданности, которая может остановить пришествие Дикой Охоты. Геральт отправляется в опасное путешествие по разоренным войной землям, чтобы найти Цири и сокрушить Дикую Охоту раз и навсегда.")
                .withGenre(Genre.Action)
                .withRatingPEGI(PEGI.PEGI18)
                .build();
        IProduct game3 = new Game.PSGameBuilder()
                .withID("G-0003")
                .withNomenclature("Cyberpunk 2077")
                .withPrice(6000)
                .withProducer("CD Projekt RED")
                .withRemain(40)
                .withActivityForSale(false)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.GAME)
                .withKeyWords(Arrays.asList(Keywords.AAA, Keywords.NEW, Keywords.PS5))
                .withDescription("игра от CD Project RED, причем отошедшая от мира фэнтези и средневековья к будущему и киберпанковскому сеттингу. События игры разворачиваются в мире настольной RPG Cyberpunk 2020, однако временные рамки сдвинуты к 2077 году. В центре внимания - протагонист с лаконичным именем Ви, который занимается различной деятельностью на грани закона, хотя в Найт-Сити закон давно существует лишь на бумаге.")
                .withGenre(Genre.Action)
                .withRatingPEGI(PEGI.PEGI16)
                .build();
        IProduct game4 = new Game.PSGameBuilder()
                .withID("G-0004")
                .withNomenclature("Days Gone")
                .withPrice(4500)
                .withProducer("Bend Studio")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.GAME)
                .withKeyWords(Arrays.asList(Keywords.AAA, Keywords.EXCLUSIVE, Keywords.PS4))
                .withDescription("приключенческий шутер про выживание в открытом мире, полном зомби, которых в этом мире называют фрикерами, а также сумасшедших людей, который игроки вольны исследовать на своих двоих или в седле верного мотоцикла.")
                .withGenre(Genre.Action)
                .withRatingPEGI(PEGI.PEGI18)
                .build();
        IProduct game5 = new Game.PSGameBuilder()
                .withID("G-0005")
                .withNomenclature("God of War")
                .withPrice(2000)
                .withProducer("SIE Santa Monica Studio")
                .withRemain(50)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.GAME)
                .withKeyWords(Arrays.asList(Keywords.AAA, Keywords.EXCLUSIVE, Keywords.PS4, Keywords.HIT))
                .withDescription("серия компьютерных игр в экшн-жанрах hack and slash и action-adventure, основанных на древнегреческой и скандинавской мифологии. Главным героем всех игр серии является спартанский воин Кратос, бросивший вызов богам.")
                .withGenre(Genre.Action)
                .withRatingPEGI(PEGI.PEGI18)
                .build();

        IProduct console1 = new Console.ConsoleBuilder()
                .withID("C-0001")
                .withNomenclature("Игровая консоль PlayStation 4 1TB GTS/HZD/SpiderM/PS+ 3мес.")
                .withPrice(30990)
                .withProducer("Sony")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.BUNDLE, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console2 = new Console.ConsoleBuilder()
                .withID("C-0002")
                .withNomenclature("Игровая консоль PlayStation 4 Rainbo 1TB Zenit. Сила Льва")
                .withPrice(33350)
                .withProducer("Sony")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.LIMITED, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(false)
                .withLimitedEdition(true)
                .withDiscount(0.02)
                .build();
        IProduct console3 = new Console.ConsoleBuilder()
                .withID("C-0003")
                .withNomenclature("Игровая консоль PlayStation 4 Rainbo 1TB Sweet")
                .withPrice(33350)
                .withProducer("Sony")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.LIMITED, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(false)
                .withLimitedEdition(true)
                .withDiscount(0.02)
                .build();
        IProduct console4 = new Console.ConsoleBuilder()
                .withID("C-0004")
                .withNomenclature("Игровая консоль PlayStation 4 Rainbo 1TB Sweet")
                .withPrice(33350)
                .withProducer("Sony")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.LIMITED, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(false)
                .withLimitedEdition(true)
                .withDiscount(0.02)
                .build();
        IProduct console5 = new Console.ConsoleBuilder()
                .withID("C-0005")
                .withNomenclature("Игровая консоль PlayStation 4 Rainbo 1TB Сборная России")
                .withPrice(33350)
                .withProducer("Sony")
                .withRemain(0)
                .withActivityForSale(false)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.SPORT, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(false)
                .withLimitedEdition(true)
                .withDiscount(0.02)
                .build();
        IProduct console6 = new Console.ConsoleBuilder()
                .withID("C-0006")
                .withNomenclature("Игровая консоль PS4 PlayStation 4 Pro 1TB + Death Stranding")
                .withPrice(35000)
                .withProducer("Sony")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.EXCLUSIVE, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.06)
                .build();
        IProduct console7 = new Console.ConsoleBuilder()
                .withID("C-0007")
                .withNomenclature("Игровая консоль PlayStation 4 Rainbo 1TB Disgusting Men")
                .withPrice(33350)
                .withProducer("Sony")
                .withRemain(16)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.SPORT, Keywords.PS4))
                .withMemory("1TB")
                .withBundle(false)
                .withLimitedEdition(true)
                .withDiscount(0)
                .build();
        IProduct console8 = new Console.ConsoleBuilder()
                .withID("C-0008")
                .withNomenclature("Игровая приставка Nintendo Switch. Особое издание Fortnite")
                .withPrice(23490)
                .withProducer("Nintendo")
                .withRemain(11)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BUNDLE, Keywords.NINTENDO))
                .withMemory("32Gb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0)
                .build();
        IProduct console9 = new Console.ConsoleBuilder()
                .withID("C-0009")
                .withNomenclature("Игровая консоль Nintendo Switch (серый)")
                .withPrice(23490)
                .withProducer("Nintendo")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.STANDART, Keywords.NINTENDO))
                .withMemory("32Gb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0)
                .build();
        IProduct console10 = new Console.ConsoleBuilder()
                .withID("C-0010")
                .withNomenclature("Игровая приставка Nintendo Switch Lite Nintendo Zacian&Zamazenta Edition")
                .withPrice(16490)
                .withProducer("Nintendo")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.HIT, Keywords.NINTENDO))
                .withMemory("32Gb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0.3)
                .build();
        IProduct console11 = new Console.ConsoleBuilder()
                .withID("C-0011")
                .withNomenclature("Игровая приставка Nintendo NES Classic Mini")
                .withPrice(3990)
                .withProducer("Nintendo")
                .withRemain(200)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.RETRO, Keywords.NINTENDO))
                .withMemory("32Gb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0.3)
                .build();
        IProduct console12 = new Console.ConsoleBuilder()
                .withID("C-0012")
                .withNomenclature("Игровая консоль Xbox One Microsoft S 1TB + Forza Horizon 4 + LEGO Speed Champions")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.XBOX, Keywords.BUNDLE))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console13 = new Console.ConsoleBuilder()
                .withID("C-0013")
                .withNomenclature("Игровая консоль Xbox One Microsoft S 1TB + Star Wars Jedi: Fallen Order")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.XBOX, Keywords.BUNDLE))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console14 = new Console.ConsoleBuilder()
                .withID("C-0014")
                .withNomenclature("Игровая консоль Microsoft Xbox One S White 1 TB + 5 игр")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.XBOX, Keywords.BUNDLE))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console15 = new Console.ConsoleBuilder()
                .withID("C-0015")
                .withNomenclature("Игровая консоль Xbox One Microsoft S 1TB + Forza Horizon 4")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.BONUS, Keywords.XBOX, Keywords.BUNDLE))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console16 = new Console.ConsoleBuilder()
                .withID("C-0016")
                .withNomenclature("Игровая консоль Xbox One Microsoft S 1 Tb (234-00013)")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.STANDART, Keywords.XBOX))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console17 = new Console.ConsoleBuilder()
                .withID("C-0017")
                .withNomenclature("Игровая консоль Xbox One Microsoft X 1TB черная+Live Gold 14дней+месяц GamePass Microsoft")
                .withPrice(33990)
                .withProducer("Microsoft")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.STANDART, Keywords.XBOX))
                .withMemory("1Tb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console18 = new Console.ConsoleBuilder()
                .withID("C-0018")
                .withNomenclature("Игровая консоль Xbox One Microsoft S 500GB + Assassin's Creed Origins")
                .withPrice(19990)
                .withProducer("Microsoft")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.STANDART, Keywords.XBOX))
                .withMemory("500Gb")
                .withBundle(true)
                .withLimitedEdition(false)
                .withDiscount(0.05)
                .build();
        IProduct console19 = new Console.ConsoleBuilder()
                .withID("C-0019")
                .withNomenclature("Игровая консоль Sony PlayStation 5")
                .withPrice(46990)
                .withProducer("Sony")
                .withRemain(1000)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.PS5, Keywords.HITS, Keywords.NEW))
                .withMemory("1Tb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0)
                .build();
        IProduct console20 = new Console.ConsoleBuilder()
                .withID("C-0020")
                .withNomenclature("Игровая консоль Sony PlayStation 5 Digital Edition")
                .withPrice(37990)
                .withProducer("Sony")
                .withRemain(1000)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.PS5, Keywords.HITS, Keywords.NEW))
                .withMemory("1Tb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0)
                .build();
        IProduct console21 = new Console.ConsoleBuilder()
                .withID("C-0021")
                .withNomenclature("Игровая приставка Microsoft Xbox Series X")
                .withPrice(45990)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.CONSOLE)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.HITS, Keywords.NEW))
                .withMemory("1Tb")
                .withBundle(false)
                .withLimitedEdition(false)
                .withDiscount(0)
                .build();

        IProduct card1 = new PaymentCard.CardBuilder()
                .withID("P-0100")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 500 руб.")
                .withPrice(500)
                .withSum(500)
                .withProducer("Sony")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card2 = new PaymentCard.CardBuilder()
                .withID("P-0101")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 1000 руб.")
                .withPrice(1000)
                .withSum(1000)
                .withProducer("Sony")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card3 = new PaymentCard.CardBuilder()
                .withID("P-0102")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 1500 руб.")
                .withPrice(1500)
                .withSum(1500)
                .withProducer("Sony")
                .withRemain(5)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card4 = new PaymentCard.CardBuilder()
                .withID("P-0102")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 2000 руб.")
                .withPrice(2000)
                .withSum(2000)
                .withProducer("Sony")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card5 = new PaymentCard.CardBuilder()
                .withID("P-0103")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 2500 руб.")
                .withPrice(2500)
                .withSum(2500)
                .withProducer("Sony")
                .withRemain(14)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card6 = new PaymentCard.CardBuilder()
                .withID("P-0104")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 5000 руб.")
                .withPrice(5000)
                .withSum(5000)
                .withProducer("Sony")
                .withRemain(50)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card7 = new PaymentCard.CardBuilder()
                .withID("P-0105")
                .withNomenclature("Playstation Store пополнение бумажника: Карта оплаты 10000 руб.")
                .withPrice(10000)
                .withSum(10000)
                .withProducer("Sony")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.PS4, Keywords.PS5, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card8 = new PaymentCard.CardBuilder()
                .withID("P-0106")
                .withNomenclature("XBOX Live Gift Card EUROPE 20 EUR Xbox Live Key")
                .withPrice(1742)
                .withSum(20)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(false)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card9 = new PaymentCard.CardBuilder()
                .withID("P-0107")
                .withNomenclature("Bundle XBOX Live Gift Card EUROPE 20 EUR Xbox Live Key + 50EUR Xbox Live Key")
                .withPrice(6515)
                .withSum(70)
                .withProducer("Microsoft")
                .withRemain(10)
                .withActivityForSale(false)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card10 = new PaymentCard.CardBuilder()
                .withID("P-0108")
                .withNomenclature("Подписка Xbox Live Gold на 6 месяцев (Цифровая версия)")
                .withPrice(1829)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(20)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card11 = new PaymentCard.CardBuilder()
                .withID("P-0109")
                .withNomenclature("Xbox Game Pass Ultimate. Подписка на 12 месяцев")
                .withPrice(10776)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card12 = new PaymentCard.CardBuilder()
                .withID("P-0110")
                .withNomenclature("Xbox Game Pass. Абонемент на 12 месяцев")
                .withPrice(7188)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card13 = new PaymentCard.CardBuilder()
                .withID("P-0111")
                .withNomenclature("Xbox Game Pass Ultimate. Подписка на 3 месяца")
                .withPrice(2694)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(1)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card14 = new PaymentCard.CardBuilder()
                .withID("P-0112")
                .withNomenclature("Xbox Game Pass ULTIMATE на 14 дней + 1 месяц")
                .withPrice(399)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card15 = new PaymentCard.CardBuilder()
                .withID("P-0113")
                .withNomenclature("Подписка Xbox LIVE: GOLD на 6 месяцев")
                .withPrice(1734)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();
        IProduct card16 = new PaymentCard.CardBuilder()
                .withID("P-0113")
                .withNomenclature("Подписка Xbox LIVE: GOLD на 12 месяцев")
                .withPrice(3539)
                .withSum(0)
                .withProducer("Microsoft")
                .withRemain(15)
                .withActivityForSale(true)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.PAYMENTCARD)
                .withKeyWords(Arrays.asList(Keywords.XBOX, Keywords.XBOXLIVE, Keywords.CARD, Keywords.PAYMENT, Keywords.WALLET))
                .build();

        IProduct accessory1 = new Accessories.AccessoryBuilder()
                .withID("A-10000")
                .withNomenclature("Геймпад Defender Game Master G2 черный")
                .withPrice(499)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("Defender")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.PC))
                .build();
        IProduct accessory2 = new Accessories.AccessoryBuilder()
                .withID("A-10001")
                .withNomenclature("Геймпад DEXP G-M1 черный")
                .withPrice(1399)
                .compatibleWith(Arrays.asList(Compatibility.Android, Compatibility.IOS))
                .withProducer("DEXP")
                .withRemain(6)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.PC))
                .build();
        IProduct accessory3 = new Accessories.AccessoryBuilder()
                .withID("A-10002")
                .withNomenclature("Геймпад DEXP G-M2 черный")
                .withPrice(1899)
                .compatibleWith(Arrays.asList(Compatibility.Android, Compatibility.IOS))
                .withProducer("DEXP")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.ANDROID, Keywords.IOS))
                .build();
        IProduct accessory4 = new Accessories.AccessoryBuilder()
                .withID("A-10003")
                .withNomenclature("Геймпад Artplays AN-201 черный")
                .withPrice(1699)
                .compatibleWith(Arrays.asList(Compatibility.Android, Compatibility.IOS, Compatibility.PC, Compatibility.PS3))
                .withProducer("Artplays")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.ANDROID, Keywords.IOS))
                .build();
        IProduct accessory5 = new Accessories.AccessoryBuilder()
                .withID("A-10004")
                .withNomenclature("Геймпад PlayStation DualSense Wireless Controller для PS5 белый")
                .withPrice(5799)
                .compatibleWith(Arrays.asList(Compatibility.PS5, Compatibility.PS4))
                .withProducer("Sony")
                .withRemain(50)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.PS5, Keywords.PS4, Keywords.NEW))
                .build();
        IProduct accessory6 = new Accessories.AccessoryBuilder()
                .withID("A-10005")
                .withNomenclature("Геймпад Hori HORIPAD черный")
                .withPrice(2199)
                .compatibleWith(Arrays.asList(Compatibility.NintendoSwitch))
                .withProducer("Hori")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.NINTENDO, Keywords.NEW))
                .build();
        IProduct accessory7 = new Accessories.AccessoryBuilder()
                .withID("A-10006")
                .withNomenclature("Игровой контроллер Nintendo Joy-Con Pair Neon Purple/Neon Orange разноцветный")
                .withPrice(6999)
                .compatibleWith(Arrays.asList(Compatibility.NintendoSwitch))
                .withProducer("Nintendo")
                .withRemain(10)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.NINTENDO, Keywords.NEW))
                .build();
        IProduct accessory8 = new Accessories.AccessoryBuilder()
                .withID("A-10007")
                .withNomenclature("Игровой контроллер Hori Pro.V Hayabusa красный")
                .withPrice(13399)
                .compatibleWith(Arrays.asList(Compatibility.NintendoSwitch))
                .withProducer("Nintendo")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.NINTENDO))
                .build();
        IProduct accessory9 = new Accessories.AccessoryBuilder()
                .withID("A-10008")
                .withNomenclature("Геймпад Microsoft Xbox WLC Carbon Black черный")
                .withPrice(4399)
                .compatibleWith(Arrays.asList(Compatibility.XboxONE, Compatibility.XboxSeriesS, Compatibility.XboxSeriesX))
                .withProducer("Microsoft")
                .withRemain(4)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.XBOX, Keywords.NEW))
                .build();
        IProduct accessory10 = new Accessories.AccessoryBuilder()
                .withID("A-10009")
                .withNomenclature("Геймпад Microsoft Xbox WLC + Беспроводной адаптер черный")
                .withPrice(5499)
                .compatibleWith(Arrays.asList(Compatibility.XboxONE, Compatibility.XboxSeriesS, Compatibility.XboxSeriesX, Compatibility.PC))
                .withProducer("Nintendo")
                .withRemain(40)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.GAMEPAD, Keywords.XBOX, Keywords.NEW, Keywords.PC))
                .build();
        IProduct accessory11 = new Accessories.AccessoryBuilder()
                .withID("A-10010")
                .withNomenclature("Виниловая наклейка голубой карбон")
                .withPrice(399)
                .compatibleWith(Arrays.asList(Compatibility.PS4))
                .withProducer("")
                .withRemain(40)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.STICKER, Keywords.PS4))
                .build();
        IProduct accessory12 = new Accessories.AccessoryBuilder()
                .withID("A-10011")
                .withNomenclature("Виниловая наклейка белый карбон")
                .withPrice(599)
                .compatibleWith(Arrays.asList(Compatibility.PS4))
                .withProducer("")
                .withRemain(40)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.STICKER, Keywords.PS4))
                .build();
        IProduct accessory13 = new Accessories.AccessoryBuilder()
                .withID("A-10012")
                .withNomenclature("Мышь беспроводная/проводная Razer Basilisk Ultimate черный")
                .withPrice(14999)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.MOUSE, Keywords.PC))
                .build();
        IProduct accessory14 = new Accessories.AccessoryBuilder()
                .withID("A-10013")
                .withNomenclature("Мышь беспроводная/проводная Razer Viper Ultimate черный")
                .withPrice(12999)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("")
                .withRemain(4)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.MOUSE, Keywords.PC))
                .build();
        IProduct accessory15 = new Accessories.AccessoryBuilder()
                .withID("A-10014")
                .withNomenclature("Клавиатура Razer Huntsman Elite")
                .withPrice(19999)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("")
                .withRemain(2)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.KEYBOARD, Keywords.PC))
                .build();
        IProduct accessory16 = new Accessories.AccessoryBuilder()
                .withID("A-10015")
                .withNomenclature("Клавиатура Logitech G915 TKL")
                .withPrice(18999)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("")
                .withRemain(0)
                .withActivityForSale(false)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.KEYBOARD, Keywords.PC))
                .build();
        IProduct accessory17 = new Accessories.AccessoryBuilder()
                .withID("A-10016")
                .withNomenclature("Очки виртуальной реальности Fibrum")
                .withPrice(3999)
                .compatibleWith(Arrays.asList(Compatibility.Android, Compatibility.IOS))
                .withProducer("")
                .withRemain(3)
                .withActivityForSale(false)
                .withActivityForOrder(false)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.VR))
                .build();
        IProduct accessory18 = new Accessories.AccessoryBuilder()
                .withID("A-10017")
                .withNomenclature("Система виртуальной реальности Playstation VR Mega Pack2 + игры Everybody’s Golf, Resident Evil 7, VR Worlds, Skyrim, Astro Bot")
                .withPrice(28999)
                .compatibleWith(Arrays.asList(Compatibility.PS4, Compatibility.PSVR))
                .withProducer("Sony")
                .withRemain(3)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.VR, Keywords.PS4, Keywords.BUNDLE))
                .build();
        IProduct accessory19 = new Accessories.AccessoryBuilder()
                .withID("A-10018")
                .withNomenclature("Система виртуальной реальности HTC Vive Cosmos")
                .withPrice(76999)
                .compatibleWith(Arrays.asList(Compatibility.PC))
                .withProducer("HTC")
                .withRemain(0)
                .withActivityForSale(true)
                .withActivityForOrder(true)
                .withNomenclatureGroup(NomenclatureGroups.ACCESSORIES)
                .withKeyWords(Arrays.asList(Keywords.VR, Keywords.PC, Keywords.NEW))
                .build();

        goodsArrList.add(game1);
        goodsArrList.add(game2);
        goodsArrList.add(game3);
        goodsArrList.add(game4);
        goodsArrList.add(game5);

        goodsArrList.add(console1);
        goodsArrList.add(console2);
        goodsArrList.add(console3);
        goodsArrList.add(console4);
        goodsArrList.add(console5);

        goodsArrList.add(console6);
        goodsArrList.add(console7);
        goodsArrList.add(console8);
        goodsArrList.add(console9);
        goodsArrList.add(console10);

        goodsArrList.add(console11);
        goodsArrList.add(console12);
        goodsArrList.add(console13);
        goodsArrList.add(console14);
        goodsArrList.add(console15);

        goodsArrList.add(console16);
        goodsArrList.add(console17);
        goodsArrList.add(console18);
        goodsArrList.add(console19);
        goodsArrList.add(console20);
        goodsArrList.add(console21);

        goodsArrList.add(card1);
        goodsArrList.add(card2);
        goodsArrList.add(card3);
        goodsArrList.add(card4);
        goodsArrList.add(card5);

        goodsArrList.add(card6);
        goodsArrList.add(card7);
        goodsArrList.add(card8);
        goodsArrList.add(card9);
        goodsArrList.add(card10);

        goodsArrList.add(card11);
        goodsArrList.add(card12);
        goodsArrList.add(card13);
        goodsArrList.add(card14);
        goodsArrList.add(card15);
        goodsArrList.add(card16);

        goodsArrList.add(accessory1);
        goodsArrList.add(accessory2);
        goodsArrList.add(accessory3);
        goodsArrList.add(accessory4);
        goodsArrList.add(accessory5);

        goodsArrList.add(accessory6);
        goodsArrList.add(accessory7);
        goodsArrList.add(accessory8);
        goodsArrList.add(accessory9);
        goodsArrList.add(accessory10);

        goodsArrList.add(accessory11);
        goodsArrList.add(accessory12);
        goodsArrList.add(accessory13);
        goodsArrList.add(accessory14);
        goodsArrList.add(accessory15);

        goodsArrList.add(accessory16);
        goodsArrList.add(accessory17);
        goodsArrList.add(accessory18);
        goodsArrList.add(accessory19);
        return goodsArrList;
    }
}
